Repository mailchimp/mailchimp-client-lib-codegen, pull requests merged in 2021-08, with the labels that each got.

#209 New github actions to allow testing on forks
  .github/workflows/create-release-marketing.yml
  .github/workflows/test-marketing.yml
  .github/workflows/validate-and-generate-marketing.yml
Labels: cla-signed

#215 Fix github action
  .github/workflows/test-marketing.yml
Labels: cla-signed, test-marketing

#220 Allow transactional fork and push testing
  .github/workflows/create-release-transactional.yml
  .github/workflows/test-transactional.yml
  .github/workflows/validate-and-generate-transactional.yml
Labels: cla-signed

#224 Rebuild Staging Docs in Workflow Run Action
  .github/workflows/build-dev-site.yml
  .github/workflows/test-marketing.yml
  .github/workflows/test-transactional.yml
Labels: cla-signed

#225 verify_txt_key parameter added to 3 /senders/ endpoints
  spec/transactional.json
Labels: cla-signed, test-transactional

#234 Trying new issue forms
  .github/ISSUE_TEMPLATE/MARKETING-ISSUE-FORM.yml
  .github/ISSUE_TEMPLATE/TRANSACTIONAL-ISSUE-FORM.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/ref_issue.md
Labels: cla-signed

#235 Create code-of-conduct
  code-of-conduct.md
Labels: cla-signed
